---
galaxy_info:
  author: "Sypchik"
  description: Install and configure ClickHouse
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
dependencies: []

